// import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
// import fs from 'fs'
// import path from 'path'
// import { db } from '@/lib/prisma'
// import { checkUser } from '@/lib/checkUser'

// export async function generateReceiptDataUrl(reportId) {
//   const user = await checkUser()
//   if (!user) return { success: false, error: 'Unauthorized' }

//   const report = await db.report.findFirst({ where: { OR: [{ id: reportId }, { reportId: reportId }] }, include: { city: true, department: true, area: true, author: true } })
//   if (!report) return { success: false, error: 'Report not found' }

//   // Only author or admins can generate
//   if (report.authorId !== user.id && user.role !== 'ADMIN' && user.role !== 'SUPER_ADMIN') {
//     return { success: false, error: 'Forbidden' }
//   }

//   // Build PDF
//   const pdfDoc = await PDFDocument.create()
//   const page = pdfDoc.addPage([612, 792])
//   const { width, height } = page.getSize()

//   const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica)
//   const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

//   // Try to embed logo if exists
//   const logoPath = path.join(process.cwd(), 'public', 'logo.png')
//   if (fs.existsSync(logoPath)) {
//     try {
//       const logoBytes = fs.readFileSync(logoPath)
//       let img
//       if (logoPath.toLowerCase().endsWith('.png')) {
//         img = await pdfDoc.embedPng(logoBytes)
//       } else {
//         img = await pdfDoc.embedJpg(logoBytes)
//       }
//       const imgDims = img.scale(0.6)
//       page.drawImage(img, { x: 40, y: height - 100, width: imgDims.width, height: imgDims.height })
//     } catch (e) {
//       // ignore
//     }
//   } else {
//     page.drawText('CivicConnect', { x: 40, y: height - 60, size: 24, font: helveticaBold, color: rgb(0.1, 0.1, 0.1) })
//   }

//   page.drawText('Acknowledgement Receipt', { x: 40, y: height - 140, size: 18, font: helveticaBold })

//   const lines = []
//   lines.push(`Reference ID: ${report.reportId}`)
//   lines.push(`Submitted At: ${report.createdAt.toISOString()}`)
//   lines.push(`Title: ${report.title}`)
//   lines.push(`Department: ${report.department?.name || 'N/A'}`)
//   lines.push(`Location: ${report.city?.name || 'N/A'}${report.area ? ' - ' + report.area.name : ''}`)
//   lines.push(`Address: ${report.description?.split('\n')[0] || 'N/A'}`)

//   let y = height - 180
//   for (const line of lines) {
//     page.drawText(line, { x: 40, y, size: 12, font: helvetica })
//     y -= 20
//   }

//   page.drawText(`This is an official acknowledgement generated by CivicConnect.`, { x: 40, y: 72, size: 9, font: helvetica })
//   page.drawText(`© ${new Date().getFullYear()} CivicConnect`, { x: 40, y: 58, size: 9, font: helvetica })

//   const pdfBytes = await pdfDoc.save()
//   const base64 = Buffer.from(pdfBytes).toString('base64')
//   const dataUrl = `data:application/pdf;base64,${base64}`

//   return { success: true, dataUrl }
// }



'use server'

import { db } from "@/lib/prisma"
import { checkUser } from "@/lib/checkUser"
import { revalidatePath } from "next/cache"
import { sendNotification } from "@/lib/notifications"
import fs from "fs"
import path from "path"
import { randomUUID } from "crypto"
import Mux from '@mux/mux-node'

// Initialize Mux with your Environment Variables
const mux = new Mux({
    accessToken: process.env.MUX_TOKEN_ID,
    secret: process.env.MUX_TOKEN_SECRET
});

// Helper: Upload a single File object to Mux (Used by WEB users)
async function uploadFileToMux(file) {
    try {
        const upload = await mux.video.uploads.create({
            new_asset_settings: { playback_policy: ['public'] }
        });
        
        await fetch(upload.url, {
            method: 'PUT',
            headers: { 'Content-Type': file.type || 'video/mp4' },
            body: Buffer.from(await file.arrayBuffer())
        });

        let asset = null;
        // Poll Mux for the asset to be ready
        for (let i = 0; i < 20; i++) {
            const list = await mux.video.assets.list({ upload_id: upload.id, limit: 1 });
            if (list.data && list.data.length > 0) {
                asset = list.data[0];
                if (asset.status === 'ready') break;
            }
            await new Promise(r => setTimeout(r, 2000));
        }
        
        if (!asset) throw new Error('Mux asset processing timed out');
        return { playbackId: asset.playback_ids?.[0]?.id, assetId: asset.id };
    } catch (err) {
        console.error("Mux Upload Error:", err);
        throw err;
    }
}

export async function createReport(formData) {
    try {
        const user = await checkUser();
        if (!user) return { success: false, error: "You must be logged in." };

        const dbUser = await db.user.findUnique({ 
            where: { id: user.id }, 
            select: { isBanned: true } 
        });
        if (dbUser?.isBanned) return { success: false, error: "Account banned." };

        // 1. Extract Fields from FormData
        const title = (formData.get("title") || "").toString().trim();
        const description = (formData.get("description") || "").toString().trim();
        const cityId = formData.get("cityId");
        const departmentId = formData.get("departmentId");
        const address = formData.get("address");
        const selectedCategory = formData.get("category");
        const customCategory = formData.get("customCategory");
        const priorityInput = formData.get("priority");
        
        const lat = parseFloat(formData.get("lat"));
        const lng = parseFloat(formData.get("lng"));
        
        const finalCategory = selectedCategory === "Other" && customCategory ? customCategory.trim() : selectedCategory;
        const detectedPriority = priorityInput === "AUTO" || !priorityInput ? "MEDIUM" : priorityInput;

        if (!title || title.length < 5) return { success: false, error: "Title too short." };
        if (!cityId || !departmentId) return { success: false, error: "City/Dept required." };

        const reportId = `RPT-${Math.floor(1000 + Math.random() * 9000)}`;
        const shareToken = `share_${Math.random().toString(36).substring(2, 15)}`;

        // --- 🎥 MOBILE BYPASS LOGIC ---
        // Capture the IDs sent from the mobile app's direct Mux upload
        const muxVideoIds = formData.getAll("muxVideoIds"); 
        const mobileVideoData = muxVideoIds.map((id, index) => ({
            playbackId: id, 
            assetId: id,
            order: index
        }));

        // 2. Create Report in DB
        const report = await db.report.create({
            data: {
                reportId,
                title,
                description: address ? `${description}\n\n📍 Location: ${address}` : description,
                status: "PENDING",
                priority: detectedPriority,
                category: finalCategory,
                latitude: Number.isFinite(lat) ? lat : null,
                longitude: Number.isFinite(lng) ? lng : null,
                shareToken,
                author: { connect: { id: user.id } },
                city: { connect: { id: cityId } },
                department: { connect: { id: departmentId } },
                // Connect mobile videos immediately
                videos: {
                    create: mobileVideoData
                },
                updates: {
                    create: { newStatus: "PENDING", note: "Report submitted", updatedBy: "system" }
                }
            }
        });

        // 3. Handle Images (Base64 storage)
        const imageFiles = formData.getAll("images").slice(0, 5);
        for (let i = 0; i < imageFiles.length; i++) {
            const file = imageFiles[i];
            if (file && file.size > 0) {
                const buffer = Buffer.from(await file.arrayBuffer());
                const base64Url = `data:${file.type || "image/jpeg"};base64,${buffer.toString("base64")}`;
                await db.reportImage.create({
                    data: { reportId: report.id, url: base64Url, order: i }
                });
                if (i === 0) {
                    await db.report.update({ where: { id: report.id }, data: { imageUrl: base64Url } });
                }
            }
        }

        // 4. Handle WEB Video Uploads (Actual Files)
        const webVideoFiles = formData.getAll("videos").filter(f => f.size > 0).slice(0, 2);
        for (let i = 0; i < webVideoFiles.length; i++) {
            try {
                const result = await uploadFileToMux(webVideoFiles[i]);
                await db.reportVideo.create({
                    data: {
                        reportId: report.id,
                        order: i + mobileVideoData.length,
                        playbackId: result.playbackId,
                        assetId: result.assetId
                    }
                });
            } catch (e) {
                console.error("Web Video processing failed:", e);
            }
        }

        if (sendNotification) {
            await sendNotification(user.id, "Report Submitted", `ID: ${reportId}`, reportId, detectedPriority).catch(() => {});
        }

        revalidatePath('/admin');
        revalidatePath('/status');

        return { success: true, reportId };

    } catch (error) {
        console.error("Submission Error:", error);
        return { success: false, error: "Failed to submit report." };
    }
}

export async function getReportByReportId(reportId) {
    try {
        const report = await db.report.findUnique({
            where: { reportId },
            include: {
                city: true,
                department: true,
                area: true,
                tags: true,
                images: { orderBy: { order: 'asc' } },
                videos: { orderBy: { order: 'asc' } },
                updates: { orderBy: { createdAt: 'desc' } }
            }
        });
        if (!report) return { success: false, error: "Not found" };
        return { success: true, report };
    } catch (error) {
        return { success: false, error: "Fetch failed" };
    }
}

export async function getUserReports() {
    try {
        const user = await checkUser();
        if (!user) return { success: false, error: "Unauthorized" };
        const reports = await db.report.findMany({
            where: { authorId: user.id },
            orderBy: { createdAt: 'desc' },
            include: { city: true, department: true, images: { take: 1 } }
        });
        return { success: true, reports };
    } catch (error) {
        return { success: false, error: "Fetch failed" };
    }
}