import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import fs from 'fs'
import path from 'path'
import { db } from '@/lib/prisma'
import { checkUser } from '@/lib/checkUser'

export async function generateReceiptDataUrl(reportId) {
  const user = await checkUser()
  if (!user) return { success: false, error: 'Unauthorized' }

  const report = await db.report.findFirst({ where: { OR: [{ id: reportId }, { reportId: reportId }] }, include: { city: true, department: true, area: true, author: true } })
  if (!report) return { success: false, error: 'Report not found' }

  // Only author or admins can generate
  if (report.authorId !== user.id && user.role !== 'ADMIN' && user.role !== 'SUPER_ADMIN') {
    return { success: false, error: 'Forbidden' }
  }

  // Build PDF
  const pdfDoc = await PDFDocument.create()
  const page = pdfDoc.addPage([612, 792])
  const { width, height } = page.getSize()

  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  // Try to embed logo if exists
  const logoPath = path.join(process.cwd(), 'public', 'logo.png')
  if (fs.existsSync(logoPath)) {
    try {
      const logoBytes = fs.readFileSync(logoPath)
      let img
      if (logoPath.toLowerCase().endsWith('.png')) {
        img = await pdfDoc.embedPng(logoBytes)
      } else {
        img = await pdfDoc.embedJpg(logoBytes)
      }
      const imgDims = img.scale(0.6)
      page.drawImage(img, { x: 40, y: height - 100, width: imgDims.width, height: imgDims.height })
    } catch (e) {
      // ignore
    }
  } else {
    page.drawText('CivicConnect', { x: 40, y: height - 60, size: 24, font: helveticaBold, color: rgb(0.1, 0.1, 0.1) })
  }

  page.drawText('Acknowledgement Receipt', { x: 40, y: height - 140, size: 18, font: helveticaBold })

  const lines = []
  lines.push(`Reference ID: ${report.reportId}`)
  lines.push(`Submitted At: ${report.createdAt.toISOString()}`)
  lines.push(`Title: ${report.title}`)
  lines.push(`Department: ${report.department?.name || 'N/A'}`)
  lines.push(`Location: ${report.city?.name || 'N/A'}${report.area ? ' - ' + report.area.name : ''}`)
  lines.push(`Address: ${report.description?.split('\n')[0] || 'N/A'}`)

  let y = height - 180
  for (const line of lines) {
    page.drawText(line, { x: 40, y, size: 12, font: helvetica })
    y -= 20
  }

  page.drawText(`This is an official acknowledgement generated by CivicConnect.`, { x: 40, y: 72, size: 9, font: helvetica })
  page.drawText(`© ${new Date().getFullYear()} CivicConnect`, { x: 40, y: 58, size: 9, font: helvetica })

  const pdfBytes = await pdfDoc.save()
  const base64 = Buffer.from(pdfBytes).toString('base64')
  const dataUrl = `data:application/pdf;base64,${base64}`

  return { success: true, dataUrl }
}